name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem would this feature solve? Why is it needed?
      placeholder: "I'm always frustrated when... It would be helpful to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "Add a new method that allows..."
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: API Example
      description: Show how you envision the API would look
      render: swift
      placeholder: |
        // Example of proposed API
        let client = GateAIClient(configuration: config)
        client.setRetryPolicy(.exponential(maxAttempts: 3))
        try await client.performProxyRequest(...)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: "I considered using... but it doesn't work because..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - "Yes, I can submit a PR"
        - "Maybe, with guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: "Other SDKs that have this feature..."
    validations:
      required: false
